# vim:ft=kitty
# # blend of https://github.com/dexpota/kitty-themes/blob/master/themes/ayu_mirage.conf and https://github.com/catppuccin/kitty/blob/main/mocha.conf

# The basic colors
background              #212733
foreground              #d9d7ce
selection_background    #343f4c
selection_foreground    #212733

# Cursor colors (from Catppuccin Mocha)
cursor                  #F5E0DC
cursor_text_color       #1E1E2E

# URL underline color when hovering with mouse
url_color               #B4BEFE

# Kitty window border colors
active_border_color     #CBA6F7
inactive_border_color   #686868
bell_border_color       #ed8274

# Tab bar colors
active_tab_foreground   #212733
active_tab_background   #CBA6F7
inactive_tab_foreground #d9d7ce
inactive_tab_background #191e2a
tab_bar_background      #191e2a

# Colors for marks
mark1_foreground #212733
mark1_background #6dcbfa
mark2_foreground #212733
mark2_background #CBA6F7
mark3_foreground #212733
mark3_background #90e1c6

# The 16 terminal colors (Ayu Mirage)
color0  #191e2a
color8  #686868
color1  #ed8274
color9  #f28779
color2  #a6cc70
color10 #bae67e
color3  #fad07b
color11 #ffd580
color4  #6dcbfa
color12 #73d0ff
color5  #cfbafa
color13 #d4bfff
color6  #90e1c6
color14 #95e6cb
color7  #c7c7c7
color15 #ffffff
