##########@###################
# ----- Standard Stuff ----- #
###########@##################

format = """$all"""
right_format = """$cmd_duration"""

[directory]
truncation_length = 10
truncate_to_repo = false
style = 'bold #4ccbe8'
before_repo_root_style = 'bold #4ccbe8'
repo_root_style = 'bold red'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
truncation_symbol = '.../'
read_only = " 󰌾"
use_logical_path = false

### Git ###

[git_branch]
symbol = " "

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
modified = '!${count}'
untracked = '?${count}'

[cmd_duration]
format = '[⏱ $duration]($style)'
min_time = 5_00
show_notifications = true
min_time_to_notify = 300_000

####@###########################
# ----- NerdFont Symbols ----- #
#####@##########################

[docker_context]
symbol = " "

[hostname]
ssh_symbol = " "

[memory_usage]
symbol = "󰍛 "

[package]
symbol = "󰏗 "

### OS SYMBOLS ###

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

### LANGUAGES / PACKAGE VERSIONS ##

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
